### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of null with Session import

### ISSUE THREAD

**Issue by indesignlatam** [jgoley/atom-autocomplete-meteor-packages#10]
[Enter steps to reproduce below:]
1. try to import import { Session } from 'meteor/session';

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [autocomplete-meteor-packages](https://github.com/jgoley/atom-autocomplete-meteor-packages) package, v1.2.0
### Stack Trace

Uncaught TypeError: Cannot read property 'length' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzaldrin/lib/filter.js:19

TypeError: Cannot read property 'length' of null
    at module.exports (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzaldrin/lib/filter.js:19:37)
    at module.exports.filter (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/fuzzaldrin/lib/fuzzaldrin.js:21:14)
    at MeteorPackagesProvider.filterPackages (/Users/pmogollon/.atom/packages/autocomplete-meteor-packages/lib/provider.coffee:74:27)
    at MeteorPackagesProvider.getSuggestions (/Users/pmogollon/.atom/packages/autocomplete-meteor-packages/lib/provider.coffee:33:10)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:310:56
    at Array.forEach (native)
    at AutocompleteManager.module.exports.AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:289:17)
    at AutocompleteManager.getSuggestionsFromProviders (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61)
    at AutocompleteManager.module.exports.AutocompleteManager.findSuggestions (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:276:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/autocomplete-plus/lib/autocomplete-manager.js:3:61
```
### Commands

```
     -3:53 core:copy (atom-text-editor.editor.is-focused)
  2x -3:52.7.0 core:paste (atom-text-editor.editor.is-focused)
     -3:51.9.0 core:undo (atom-text-editor.editor.is-focused)
     -3:51.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -3:51 core:undo (atom-text-editor.editor.is-focused)
     -3:50.5.0 core:paste (atom-text-editor.editor.is-focused)
  2x -3:50 editor:newline (atom-text-editor.editor.is-focused)
     -3:49.7.0 core:paste (atom-text-editor.editor.is-focused)
  3x -3:48.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:38.4.0 core:save (atom-text-editor.editor.is-focused)
  6x -1:11.8.0 emmet:expand-abbreviation-with-tab (atom-text-editor.editor.is-focused)
     -1:06.4.0 core:save (atom-text-editor.editor.is-focused)
     -0:08.7.0 core:copy (atom-text-editor.editor.is-focused)
  2x -0:08.0 core:paste (atom-text-editor.editor.is-focused)
     -0:04.0 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -0:04.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "meteor-snippets",
      "js-autoimport",
      "linter-csslint",
      "semantic-ui",
      "meteor-helper",
      "react",
      "es6-javascript"
    ],
    "openEmptyEditorOnStart": false
  }
}
```
### Installed Packages

``` coffee
# User
autocomplete-js-import, v1.0.1
autocomplete-meteor-packages, v1.2.0
emmet, v2.4.3
linter, v1.11.14
linter-eslint, v7.2.4
meteor-api, v2.20.0
template-generator, v0.12.2

# Dev
No dev packages
```

**Comment by jgoley** [comment]
@indesignlatam Thanks for reporting this issue. It should be fixed in the latest version
